// ---- O mu Bu mu ----
const BU_MU_SU_MU_PAIRS = [
  { a: "Pizza", b: "Burger" },
  { a: "Deniz", b: "Dağ" },
  { a: "Sabah insanı", b: "Gece kuşu" },
  { a: "Kahve", b: "Çay" },
  { a: "Sinema", b: "Dizi gecesi" },
  { a: "Yaz", b: "Kış" },
  { a: "Köpek", b: "Kedi" },
  { a: "Kitap", b: "Film" },
  { a: "Şehir hayatı", b: "Doğa hayatı" },
  { a: "Planlı tatil", b: "Rastgele gezi" },
  { a: "Ev yemeği", b: "Dışarıda yemek" },
  { a: "Mesajlaşmak", b: "Telefonda konuşmak" },
  { a: "Erken kalkmak", b: "Geç kalkmak" },
  { a: "Tatlı", b: "Tuzlu" },
  { a: "Yürüyüş", b: "Bisiklet" },
  { a: "Konser", b: "Tiyatro" },
  { a: "Kamp", b: "Otel" },
  { a: "Ev partisi", b: "Dışarı çıkmak" },
  { a: "El yazısı mektup", b: "Mesaj" },
  { a: "Sürpriz plan", b: "Planlı organizasyon" },
  { a: "Balkon manzarası", b: "Deniz manzarası" },
  { a: "Piknik", b: "Restoran" },
  { a: "Yıldızları izlemek", b: "Şehir ışıkları" },
  { a: "Sessiz bir akşam", b: "Kalabalık bir davet" },
];

// ---- Çift Oyunu (Doğruluk mu Cesaret mi) ----
const TRUTH_QUESTIONS = [
  "İlk kez benden ne zaman hoşlandığını fark ettin?",
  "Hakkımda başkalarına söylemediğin bir düşüncen var mı?",
  "İlişkimizde en çok neyi değiştirmek isterdin?",
  "Benimle ilgili ilk izlenimin neydi?",
  "En unutamadığın anımız hangisi?",
  "Benden gizlediğin küçük bir alışkanlığın var mı?",
  "Kıskandığın bir an oldu mu, ne zamandı?",
  "Bana söylemekten çekindiğin bir şey var mı?",
  "Hayalindeki bir yıl dönümü nasıl olurdu?",
  "İlişkimizde en gurur duyduğun şey ne?",
  "Bir günlüğüne benim yerimde olsan ne yapardın?",
  "En çok hangi anımızı tekrar yaşamak isterdin?",
  "Benimle ilgili değiştirmek yerine kabullendiğin bir şey var mı?",
  "Bugüne kadar söylemediğin bir 'teşekkür ederim' var mı?",
  "Beni en çok ne zaman özel hissettirdin?",
  "İlişkimizin en zor anı hangisiydi, nasıl aştık?",
  "Benimle ilgili en sevdiğin küçük detay ne?",
  "Gelecekle ilgili en çok neyi merak ediyorsun?",
  "Benden öğrendiğin bir şey var mı?",
  "Şu an aklından geçen ama söylemediğin bir şey var mı?",
];

const DARE_CHALLENGES = [
  "Partnerine gözlerinin içine bakarak 30 saniye boyunca hiç konuşmadan gül.",
  "Partnerine sevdiğin 3 özelliğini söyle.",
  "Partnerinin taklidini yap.",
  "Birlikte 1 dakikalık kısa bir dans edin.",
  "Partnerine bir şarkının nakaratını söyle.",
  "Partnerine ilk tanıştığınız anı canlandırarak anlat.",
  "Partnerine el yazısıyla küçük bir not yaz ve hemen ver.",
  "Partnerine gözlerin kapalıyken sarıl.",
  "Partnerine en komik anınızı anlat ve bitirmeden gülme.",
  "Partnerine bir iltifat et ama hiç gülümsemeden söyle.",
  "Partnerinle alnınızı birleştirip 20 saniye öyle kalın.",
  "Partnerine gelecekle ilgili küçük bir hayalini anlat.",
  "Partnerine bir şeyi ilk kez itiraf et (küçük ve tatlı bir şey olsun).",
  "Partnerine onu neden seçtiğini tek cümleyle anlat.",
  "Partnerinin en sevdiği anını senin ağzından anlat.",
  "1 dakika boyunca sadece iltifatlarla konuş.",
  "Partnerine minik bir şarkı besteleyip söyle.",
  "Partnerine elini tutup gözlerinin rengini tarif et.",
  "Partnerine bir sonraki randevu fikrini şimdi öner.",
  "Partnerine sarılıp 10 saniye hiç bırakma.",
];

// ---- Tarot ----
const TAROT_DECK = [
  { name: "Deli", upright: "Yeni bir başlangıç, cesaret ve bilinmeyene atılan bir adım. Saf potansiyel seninle.", reversedText: "Düşüncesizlik ya da harekete geçmekten duyulan korku. Bir adım atmadan önce biraz daha düşün." },
  { name: "Büyücü", upright: "Elindeki kaynakları kullanma zamanı. İstediğini gerçeğe dönüştürecek güç sende.", reversedText: "Potansiyelini tam kullanamıyor olabilirsin. Manipülasyona dikkat et." },
  { name: "Azize", upright: "Sezgilerine güven. Henüz açığa çıkmamış bir bilgi ya da gerçek yakında ortaya çıkacak.", reversedText: "İç sesini bastırıyor olabilirsin. Sırlar ortaya çıkmaya hazır olmayabilir." },
  { name: "İmparatoriçe", upright: "Bereket, yaratıcılık ve bolluk dönemi. Kendine ve doğana bakım göster.", reversedText: "Tıkanmış bir yaratıcılık ya da kendine bakımı ihmal etme hali." },
  { name: "İmparator", upright: "Yapı, disiplin ve kontrol. Sağlam temeller kurma zamanı.", reversedText: "Aşırı katılık ya da kontrolü kaybetme korkusu." },
  { name: "Aziz", upright: "Geleneksel bilgelik, rehberlik ve öğrenme. Bir akıl hocasından ders alabilirsin.", reversedText: "Kalıpları sorgulama, kendi yolunu çizme zamanı." },
  { name: "Aşıklar", upright: "Uyum, bağlantı ve önemli bir seçim. Kalbinin sesini dinle.", reversedText: "Uyumsuzluk ya da zor bir karar karşısında kararsızlık." },
  { name: "Savaş Arabası", upright: "İrade gücü, kararlılık ve zafer. Hedefine doğru ilerliyorsun.", reversedText: "Yön kaybı ya da kontrolü elinde tutamama hissi." },
  { name: "Güç", upright: "İçsel güç, cesaret ve şefkat. Zorlukları nezaketle aşabilirsin.", reversedText: "Özgüven eksikliği ya da kendine karşı sabırsızlık." },
  { name: "Ermiş", upright: "İçe dönüş ve yalnız kalma ihtiyacı. Cevaplar içinde saklı.", reversedText: "Aşırı izolasyon ya da yalnızlıktan kaçış." },
  { name: "Kader Çarkı", upright: "Değişim, döngüler ve kader. Yeni bir dönemin eşiğindesin.", reversedText: "Kontrolünde olmayan bir değişime direniyor olabilirsin." },
  { name: "Adalet", upright: "Denge, gerçek ve sonuçlarla yüzleşme. Adil bir karar yakın.", reversedText: "Adaletsizlik hissi ya da sorumluluktan kaçış." },
  { name: "Asılan Adam", upright: "Bekleyiş, teslimiyet ve farklı bir bakış açısı. Acele etme.", reversedText: "Gereksiz bir fedakarlık ya da ilerlemede tıkanıklık." },
  { name: "Ölüm", upright: "Bir dönemin sonu, dönüşüm ve yeniden doğuş. Bırakmak, yer açar.", reversedText: "Değişime direnme ya da geçmişe sıkı sıkıya tutunma." },
  { name: "Denge", upright: "Uyum, sabır ve orta yolu bulma. Dengeyi koruyorsun.", reversedText: "Aşırılıklar ya da hayatındaki dengesizlik." },
  { name: "Şeytan", upright: "Bağımlılık, bağlanma ve gölge yönlerle yüzleşme zamanı.", reversedText: "Zincirlerinden kurtulma ve özgürleşme süreci." },
  { name: "Kule", upright: "Ani bir yıkım ya da beklenmedik bir değişim. Sarsıcı ama gerekli.", reversedText: "Kaçınılan bir yıkımın ertelenmesi, içsel bir sarsıntı." },
  { name: "Yıldız", upright: "Umut, ilham ve iyileşme. Karanlık bir dönemin ardından ışık göründü.", reversedText: "Umutsuzluk ya da kendine olan inancı kaybetme." },
  { name: "Ay", upright: "Belirsizlik, sezgi ve bilinçaltı. Her şey göründüğü gibi olmayabilir.", reversedText: "Kafa karışıklığının dağılması, netliğe kavuşma." },
  { name: "Güneş", upright: "Neşe, başarı ve netlik. Önündeki dönem aydınlık ve olumlu.", reversedText: "Geçici bir karamsarlık, ama güneş yine de yakında doğacak." },
  { name: "Mahkeme", upright: "Uyanış, hesaplaşma ve yeniden doğuş. Geçmişi değerlendirme zamanı.", reversedText: "Kendine karşı aşırı eleştirel olma ya da geçmişten ders çıkaramama." },
  { name: "Dünya", upright: "Tamamlanma, bütünlük ve başarı. Bir döngüyü tamamladın.", reversedText: "Yarım kalmış bir hedef ya da kapanışa direnme." },
];

// ---- Sevgi Dili Testi ----
const LOVE_LANGUAGE_QUESTIONS = [
  {
    q: "Partnerin sana en çok ne zaman değerli hissettirir?",
    options: [
      { text: "Bana güzel, içten sözler söylediğinde.", type: "sozler" },
      { text: "Telefonları bırakıp sadece bana zaman ayırdığında.", type: "zaman" },
      { text: "Beni düşünerek küçük bir hediye aldığında.", type: "hediye" },
      { text: "Benim için bir işi üstlenip kolaylaştırdığında.", type: "hizmet" },
      { text: "Sarılıp elimi tuttuğunda.", type: "temas" },
    ],
  },
  {
    q: "Kötü bir gün geçirdiğinde en çok neye ihtiyaç duyarsın?",
    options: [
      { text: "Beni anladığını söyleyen birkaç cümleye.", type: "sozler" },
      { text: "Yanımda oturup dinlemesine.", type: "zaman" },
      { text: "Moralimi yükseltecek küçük bir jest ya da hediyeye.", type: "hediye" },
      { text: "Yükümü hafifletecek somut bir yardıma.", type: "hizmet" },
      { text: "Sıkıca bir sarılmaya.", type: "temas" },
    ],
  },
  {
    q: "Partnerine sevgini en çok nasıl gösterirsin?",
    options: [
      { text: "Ona ne kadar değerli olduğunu söyleyerek.", type: "sozler" },
      { text: "Ona vakit ayırarak, birlikte anlar yaratarak.", type: "zaman" },
      { text: "Küçük sürprizler ve hediyeler hazırlayarak.", type: "hediye" },
      { text: "Onun işini kolaylaştıracak şeyler yaparak.", type: "hizmet" },
      { text: "Fiziksel yakınlık göstererek.", type: "temas" },
    ],
  },
  {
    q: "İdeal bir yıl dönümü nasıl geçer?",
    options: [
      { text: "Birbirimize anlamlı sözler söylediğimiz bir akşam.", type: "sozler" },
      { text: "Telefonsuz, sadece ikimize ayrılmış uzun bir gün.", type: "zaman" },
      { text: "Özenle seçilmiş bir hediye alışverişi.", type: "hediye" },
      { text: "Partnerimin benim için özel bir şey hazırlaması.", type: "hizmet" },
      { text: "Yakın, sıcak ve dokunsal bir akşam.", type: "temas" },
    ],
  },
  {
    q: "Seni en çok ne kırar?",
    options: [
      { text: "Sert ya da umursamaz sözler.", type: "sozler" },
      { text: "Bana zaman ayırmaması, hep meşgul olması.", type: "zaman" },
      { text: "Özel günleri unutması.", type: "hediye" },
      { text: "Yardım isteyince görmezden gelmesi.", type: "hizmet" },
      { text: "Fiziksel olarak mesafeli davranması.", type: "temas" },
    ],
  },
  {
    q: "Bir hediye aldığında en çok neyi önemsersin?",
    options: [
      { text: "Hediyeyle birlikte gelen anlamlı notu.", type: "sozler" },
      { text: "Hediyeyi seçerken harcadığı zamanı.", type: "zaman" },
      { text: "Hediyenin kendisini, düşünceyi.", type: "hediye" },
      { text: "Hediyenin bir ihtiyacımı çözmesini.", type: "hizmet" },
      { text: "Hediyeyi verirken sarılmasını.", type: "temas" },
    ],
  },
  {
    q: "Uzun bir iş gününün ardından eve geldiğinde ne seni mutlu eder?",
    options: [
      { text: "\"Seni özledim\" demesi.", type: "sozler" },
      { text: "Birlikte oturup günü konuşmamız.", type: "zaman" },
      { text: "Beni düşünüp bir şey almış olması.", type: "hediye" },
      { text: "Yemeği hazırlamış olması.", type: "hizmet" },
      { text: "Kapıda sıcak bir sarılma.", type: "temas" },
    ],
  },
  {
    q: "Bir ilişkide sana göre en önemli şey nedir?",
    options: [
      { text: "Açık ve içten iletişim.", type: "sozler" },
      { text: "Birlikte geçirilen kaliteli zaman.", type: "zaman" },
      { text: "Düşünceli jestler.", type: "hediye" },
      { text: "Birbirine pratik destek olmak.", type: "hizmet" },
      { text: "Fiziksel yakınlık ve sıcaklık.", type: "temas" },
    ],
  },
];

const LOVE_LANGUAGE_RESULTS = {
  sozler: {
    title: "Onaylayıcı Sözler",
    tagline: "Kelimeler senin için her şeyi değiştirir",
    text: "Senin için sevgi, söylenen sözlerde saklı. Birinin sana \"seninle gurur duyuyorum\", \"seni seviyorum\" ya da \"harikasın\" demesi, kalbine dokunan en güçlü şey. Sert ya da umursamaz sözler ise seni diğer insanlardan çok daha derinden yaralayabilir.",
    tip: "Partnerine ihtiyacını söyle: ondan daha sık içten sözler duymak istediğini paylaşmak, ilişkinizi güçlendirecek.",
  },
  zaman: {
    title: "Nitelikli Zaman",
    tagline: "Senin için en değerli hediye, tam dikkat",
    text: "Senin için sevgi, birinin sana tam olarak odaklanmış zaman ayırmasıdır. Telefonlar bir kenarda, sadece ikinizin olduğu anlar, sana kendini gerçekten değerli hissettirir. Meşguliyet ya da dikkat dağınıklığı, seni yalnız hissettirebilir.",
    tip: "Partnerine, birlikte geçirdiğiniz kesintisiz zamanın senin için ne kadar önemli olduğunu hatırlat.",
  },
  hediye: {
    title: "Hediyeler",
    tagline: "Küçük bir jest, senin için büyük bir anlam taşır",
    text: "Senin için önemli olan hediyenin maddi değeri değil, arkasındaki düşünce. Birinin seni aklında tutup küçük bir şey getirmesi, sana ne kadar değerli olduğunu hissettirir. Özel günlerin unutulması ise seni derinden üzebilir.",
    tip: "Pahalı hediyeler beklemediğini, küçük ve düşünceli jestlerin senin için yeterli olduğunu partnerinle paylaş.",
  },
  hizmet: {
    title: "Hizmet Eylemleri",
    tagline: "Senin için eylemler, sözlerden daha yüksek sesle konuşur",
    text: "Senin için sevgi, biri senin yükünü hafiflettiğinde hissedilir. Bir işi üstlenmek, yardım etmek, kolaylaştırmak — bunlar senin için en anlamlı sevgi gösterileri. Söz verilip yapılmayan şeyler ise seni hayal kırıklığına uğratabilir.",
    tip: "Partnerine hangi somut yardımların senin için en çok anlam ifade ettiğini açıkça söyle.",
  },
  temas: {
    title: "Fiziksel Temas",
    tagline: "Senin için bir sarılma, bin kelimeye bedel",
    text: "Senin için sevgi, fiziksel yakınlıkla somutlaşır. Bir el tutuşu, bir sarılma, yakın oturmak — bunlar sana güven ve sıcaklık verir. Fiziksel mesafe ise seni duygusal olarak da uzaklaşmış hissettirebilir.",
    tip: "Partnerine fiziksel yakınlığın senin için ne kadar önemli olduğunu, küçük dokunuşların bile fark yarattığını anlat.",
  },
};

// ---- Burçlar ----
const ELEMENT_LABELS = { ates: "Ateş", toprak: "Toprak", hava: "Hava", su: "Su" };

const ZODIAC_SIGNS = [
  {
    id: "koc", name: "Koç", symbol: "♈", range: "21 Mart - 19 Nisan", element: "ates",
    planet: "Mars", luckyColor: "Kırmızı", luckyNumber: 9, luckyDay: "Salı",
    strengths: ["Cesur", "Enerjik", "Girişken"], weaknesses: ["Sabırsız", "Aceleci"],
    compatibleWith: ["aslan", "yay"],
    trait: "Koç, zodyağın öncüsüdür — her zaman ilk adımı atmaya hazırdır. Cesareti ve kararlılığıyla çevresine ilham verir, ama bazen düşünmeden harekete geçme eğilimi başına iş açabilir. Rekabeti sever ve kazanmak onun için sadece bir sonuç değil, bir tutkudur."
  },
  {
    id: "boga", name: "Boğa", symbol: "♉", range: "20 Nisan - 20 Mayıs", element: "toprak",
    planet: "Venüs", luckyColor: "Yeşil", luckyNumber: 6, luckyDay: "Cuma",
    strengths: ["Kararlı", "Güvenilir", "Sadık"], weaknesses: ["İnatçı", "Değişime kapalı"],
    compatibleWith: ["basak", "oglak"],
    trait: "Boğa, sağlamlığın ve istikrarın simgesidir. Konfor ve güzelliğe düşkündür, hayattaki basit zevklerin kıymetini iyi bilir. Bir kez karar verdi mi geri adım atmaz; bu onu hem güvenilir hem de zaman zaman fazlasıyla inatçı yapar."
  },
  {
    id: "ikizler", name: "İkizler", symbol: "♊", range: "21 Mayıs - 20 Haziran", element: "hava",
    planet: "Merkür", luckyColor: "Sarı", luckyNumber: 5, luckyDay: "Çarşamba",
    strengths: ["Zeki", "Meraklı", "İletişimci"], weaknesses: ["Kararsız", "Dağınık"],
    compatibleWith: ["terazi", "kova"],
    trait: "İkizler'in zihni durmadan çalışır; her konuya meraklıdır ve yeni fikirlerle beslenir. Konuşma yeteneği ve zekâsıyla her ortama uyum sağlar, ama bu çok yönlülük bazen odaklanmakta zorlanmasına neden olabilir."
  },
  {
    id: "yengec", name: "Yengeç", symbol: "♋", range: "21 Haziran - 22 Temmuz", element: "su",
    planet: "Ay", luckyColor: "Gümüş", luckyNumber: 2, luckyDay: "Pazartesi",
    strengths: ["Şefkatli", "Sezgisel", "Koruyucu"], weaknesses: ["Alıngan", "Aşırı duygusal"],
    compatibleWith: ["akrep", "balik"],
    trait: "Yengeç, duygusal derinliğiyle tanınır. Sevdiklerini koruma içgüdüsü çok güçlüdür ve evi, ailesi onun için her şeyden değerlidir. Hassasiyeti onu güçlü bir empati kaynağı yapar, ama aynı zamanda kolayca incinebilir."
  },
  {
    id: "aslan", name: "Aslan", symbol: "♌", range: "23 Temmuz - 22 Ağustos", element: "ates",
    planet: "Güneş", luckyColor: "Altın", luckyNumber: 1, luckyDay: "Pazar",
    strengths: ["Karizmatik", "Cömert", "Lider ruhlu"], weaknesses: ["Kibirli", "İnatçı"],
    compatibleWith: ["koc", "yay"],
    trait: "Aslan, girdiği her ortamda kendini hissettirir. Doğal bir sahne ışığı çeker, cömertliği ve sıcaklığıyla insanları etrafında toplar. Takdir edilmeye ihtiyaç duyar ve kontrolü elden bırakmaktan hoşlanmaz."
  },
  {
    id: "basak", name: "Başak", symbol: "♍", range: "23 Ağustos - 22 Eylül", element: "toprak",
    planet: "Merkür", luckyColor: "Lacivert", luckyNumber: 5, luckyDay: "Çarşamba",
    strengths: ["Analitik", "Düzenli", "Yardımsever"], weaknesses: ["Aşırı eleştirel", "Kaygılı"],
    compatibleWith: ["boga", "oglak"],
    trait: "Başak, detaylara olan hassasiyetiyle öne çıkar. Mükemmeliyetçiliği onu güvenilir ve titiz bir çalışan yapar, çevresindekilere sessizce ama derinden yardım eder. Bazen kendine karşı fazla eleştirel olabilir."
  },
  {
    id: "terazi", name: "Terazi", symbol: "♎", range: "23 Eylül - 22 Ekim", element: "hava",
    planet: "Venüs", luckyColor: "Pastel tonlar", luckyNumber: 6, luckyDay: "Cuma",
    strengths: ["Diplomatik", "Adil", "Sosyal"], weaknesses: ["Kararsız", "Çatışmadan kaçan"],
    compatibleWith: ["ikizler", "kova"],
    trait: "Terazi, uyum ve denge arayışındadır. Estetikten ve güzellikten hoşlanır, ilişkilerinde adaleti önemser. Herkesi memnun etmeye çalışırken bazen kendi ihtiyaçlarını ikinci plana atabilir."
  },
  {
    id: "akrep", name: "Akrep", symbol: "♏", range: "23 Ekim - 21 Kasım", element: "su",
    planet: "Plüton", luckyColor: "Bordo", luckyNumber: 8, luckyDay: "Salı",
    strengths: ["Tutkulu", "Kararlı", "Sadık"], weaknesses: ["Kıskanç", "Gizemli/kapalı"],
    compatibleWith: ["yengec", "balik"],
    trait: "Akrep, yoğun ve derin duygularıyla bilinir. Bir kez bağlandı mı sonsuz sadakat gösterir, ama güveni kazanmak kolay değildir. Gizemi ve sezgisel gücü, onu zodyağın en dikkat çekici burçlarından biri yapar."
  },
  {
    id: "yay", name: "Yay", symbol: "♐", range: "22 Kasım - 21 Aralık", element: "ates",
    planet: "Jüpiter", luckyColor: "Mor", luckyNumber: 3, luckyDay: "Perşembe",
    strengths: ["İyimser", "Maceracı", "Dürüst"], weaknesses: ["Sabırsız", "Taktsiz"],
    compatibleWith: ["koc", "aslan"],
    trait: "Yay, özgürlüğüne düşkün, ufku geniş bir gezgindir. Hayata iyimser bakar, yeni deneyimlerden ve bilgiden beslenir. Dürüstlüğü bazen fazla doğrudan gelebilir, ama art niyeti asla yoktur."
  },
  {
    id: "oglak", name: "Oğlak", symbol: "♑", range: "22 Aralık - 19 Ocak", element: "toprak",
    planet: "Satürn", luckyColor: "Kahverengi", luckyNumber: 4, luckyDay: "Cumartesi",
    strengths: ["Disiplinli", "Hırslı", "Sorumlu"], weaknesses: ["Katı", "Kötümser olabilir"],
    compatibleWith: ["boga", "basak"],
    trait: "Oğlak, hedeflerine sabırla ve disiplinle ilerler. Sorumluluk duygusu güçlüdür, başarıyı adım adım inşa eder. Bazen kendine karşı çok katı olabilir, dinlenmeyi ihmal edebilir."
  },
  {
    id: "kova", name: "Kova", symbol: "♒", range: "20 Ocak - 18 Şubat", element: "hava",
    planet: "Uranüs", luckyColor: "Elektrik mavisi", luckyNumber: 7, luckyDay: "Cumartesi",
    strengths: ["Özgün", "Bağımsız", "Vizyoner"], weaknesses: ["Duygusal mesafeli", "İnatçı"],
    compatibleWith: ["ikizler", "terazi"],
    trait: "Kova, sıra dışı fikirleriyle geleceği şekillendirmeyi sever. Bağımsızlığına düşkündür, kalıplara sığmaktan hoşlanmaz. İnsancıl ve vizyoner bir bakışı vardır, ama duygusal olarak mesafeli görünebilir."
  },
  {
    id: "balik", name: "Balık", symbol: "♓", range: "19 Şubat - 20 Mart", element: "su",
    planet: "Neptün", luckyColor: "Deniz yeşili", luckyNumber: 3, luckyDay: "Perşembe",
    strengths: ["Yaratıcı", "Empatik", "Sezgisel"], weaknesses: ["Aşırı hassas", "Gerçeklikten kaçabilir"],
    compatibleWith: ["yengec", "akrep"],
    trait: "Balık, zodyağın en hayalperest ve empatik burcudur. Sanata ve maneviyata derin bir bağı vardır, başkalarının duygularını kendi duyguları gibi hisseder. Bazen gerçeklikten kaçıp hayal dünyasına sığınabilir."
  },
];

const HOROSCOPE_POOLS = {
  genel: [
    "Bugün sezgilerine her zamankinden daha çok güvenmelisin, iç sesin seni doğru yere götürüyor.",
    "Çevrendekilerle kurduğun bağlar bugün beklenmedik bir şekilde güçlenebilir.",
    "Küçük bir değişiklik, gün içinde büyük bir fark yaratacak.",
    "Bugün sabırlı olman gereken bir konu ortaya çıkabilir, aceleye getirme.",
    "Enerjini doğru yöne kanalize edersen gün senin lehine dönebilir.",
    "Geçmişte bıraktığın bir mesele bugün tekrar gündeme gelebilir, bu senin için bir fırsat.",
    "Bugün yalnız kalmaya değil, paylaşmaya ihtiyacın olabilir.",
    "Kendine ayırdığın zaman, bugün sana en çok iyi gelecek şey olacak.",
    "Bir karar vermeden önce bir kez daha düşünmen faydana olacak.",
    "Bugün şans senden yana, ama fırsatı yakalamak sana kalmış.",
    "İçindeki huzursuzluk, aslında bir değişim isteğinin işareti olabilir.",
    "Bugün çevrenden gelecek küçük bir jest, moralini yükseltecek.",
    "Bugün planların değişebilir, ama bu değişim seni daha iyi bir yere götürecek.",
    "Uzun zamandır beklediğin bir haber bugün ya da yakın günlerde gelebilir.",
    "Bugün biriyle kurduğun bağlantı, uzun vadede önemli bir dostluğa dönüşebilir.",
    "İçindeki çocuğu dinlemek, bugün sana beklenmedik bir mutluluk verecek.",
    "Bugün bir konuda net bir karara varman, üzerindeki yükü hafifletecek.",
    "Evrenin sana gönderdiği işaretlere bugün daha dikkatli bak.",
    "Bugün etrafındakilere gösterdiğin anlayış, sana kat kat geri dönecek.",
    "Küçük bir tesadüf, bugün sana beklenmedik bir kapı aralayabilir.",
  ],
  ask: [
    "Aşk hayatında beklenmedik bir gelişme seni şaşırtabilir, açık fikirli ol.",
    "Bugün duygularını ifade etmekten çekinme, karşındaki bunu takdir edecek.",
    "Bekar olanlar için gün, tanışma ihtimali yüksek bir gün.",
    "İlişkinde küçük bir yanlış anlaşılma varsa, bugün konuşarak çözebilirsin.",
    "Kalbin bugün sana ne istediğini çok net söylüyor, dinlemeye değer.",
    "Geçmişten biri bugün aklına gelebilir, ama bu bir işaret olmak zorunda değil.",
    "Bugün partnerine göstereceğin küçük bir ilgi, ilişkinizi güçlendirecek.",
    "Yalnız olmak bugün seni rahatsız etmiyor, kendinle barışıksın.",
    "Aşk konusunda bugün risk almak sana yakışacak.",
    "Duygusal olarak biraz hassas olabilirsin, kendine nazik davran.",
    "Bugün biriyle kurduğun sohbet, beklediğinden daha anlamlı olabilir.",
    "İlişkinde uzun zamandır ertelediğin bir konuşmayı yapmak için uygun bir gün.",
    "Bugün flört etme enerjin yüksek, çevrende fark edilebilirsin.",
    "İlişkinde rutine giren bir şeyi bugün değiştirmek size iyi gelecek.",
    "Bugün kıskançlık gibi duygulara kapılmadan önce bir nefes al.",
    "Uzak mesafeli bir ilişkin varsa, bugün özlemin biraz azalabilir.",
    "Bugün birine söylemek istediğin ama çekindiğin bir şeyi söylemenin tam zamanı.",
    "Aşk hayatında bugün sabrın en değerli özelliğin olacak.",
    "Bugün partnerinle ortak bir plan yapmak ilişkinizi tazeleyecek.",
    "Kendini sevme biçimin, bugün başkalarını nasıl sevdiğini de şekillendiriyor.",
  ],
  kariyer: [
    "İş hayatında attığın adımlar kısa sürede karşılığını verecek.",
    "Bugün bir teklif ya da fırsatla karşılaşabilirsin, dikkatli değerlendir.",
    "Ekip içinde liderlik etmen gereken bir an ortaya çıkabilir.",
    "Finansal konularda bugün temkinli davranman senin yararına olacak.",
    "Uzun zamandır ertelediğin bir işi bitirmek için enerjin yerinde.",
    "Bugün yeni bir fikir aklına gelebilir, not almayı unutma.",
    "İş yerinde biriyle yaşadığın gerginlik bugün çözüme kavuşabilir.",
    "Emeğinin karşılığını görmek için sabırlı olman gerekebilir.",
    "Bugün küçük bir risk, kariyerinde büyük bir kapı açabilir.",
    "Odaklanman gereken bir gün, dikkatini dağıtan şeylerden uzak dur.",
    "Bugün aldığın bir karar, ileride seni haklı çıkaracak.",
    "Yeni bir iş birliği ya da ortaklık teklifi gündemine girebilir.",
    "Bugün bir toplantı ya da görüşme beklediğinden daha verimli geçebilir.",
    "Uzun vadeli bir hedefe bugün küçük ama önemli bir adım atabilirsin.",
    "Bugün bir konuda 'hayır' demen, ileride seni rahatlatacak.",
    "İş yerinde bugün gösterdiğin performans, fark edilme ihtimali yüksek.",
    "Bugün beklenmedik bir masraf çıkabilir, bütçeni gözden geçir.",
    "Yeni bir beceri öğrenmeye bugün başlarsan, ileride büyük fayda sağlayacak.",
    "Bugün bir konuda inisiyatif alman, seni öne çıkaracak.",
    "Kariyerinde bugün sabrın, aceleciliğe göre daha çok işine yarayacak.",
  ],
  enerji: [
    "Bugün enerjin yüksek, bunu değerlendirmek için doğru zaman.",
    "Bedeninin sana verdiği sinyalleri dinle, dinlenmeye ihtiyacın olabilir.",
    "Küçük bir yürüyüş bile bugün zihnini çok rahatlatacak.",
    "Bugün kendine iyi bakmak, yapabileceğin en değerli şey.",
    "İçindeki huzursuzluk hareket ederek dağılabilir.",
    "Uykuna dikkat etmen gereken bir dönemdesin.",
    "Bugün pozitif enerjin çevrene de yayılacak.",
    "Biraz yavaşlamak, bugün sana daha çok iyi gelecek.",
    "Ruhsal olarak kendini yenilemek için iyi bir gün.",
    "Bugün doğayla ya da açık havayla bağlantı kurmak sana iyi gelecek.",
    "İçsel dengeyi bulmak için bugün küçük bir mola yeterli olabilir.",
    "Enerjini korumak için bugün 'hayır' demeyi öğrenmelisin.",
    "Bugün suyunu bol içmen, hem bedenine hem zihnine iyi gelecek.",
    "Meditasyon ya da nefes egzersizi bugün sana beklenmedik bir huzur getirebilir.",
    "Bugün bedenin dinlenme istiyor olabilir, kendini zorlama.",
    "Küçük bir hareket rutini, bugün enerjini toparlamana yardımcı olacak.",
    "Bugün ekrandan biraz uzaklaşman zihnini tazeleyecek.",
    "İçindeki yaratıcı enerji bugün dışa vurulmayı bekliyor.",
    "Bugün erkenden yatman, yarın için sana büyük fark yaratacak.",
    "Bugün kendine söylediğin sözlere dikkat et, enerjini şekillendiriyorlar.",
  ],
  tavsiye: [
    "Bugünün önerisi: içinden geleni ertelemeden yap.",
    "Bugünün önerisi: bir kişiye teşekkür etmek için zaman ayır.",
    "Bugünün önerisi: telefonunu bırak, anın tadını çıkar.",
    "Bugünün önerisi: 'hayır' demekten çekinme.",
    "Bugünün önerisi: küçük bir hedef koy ve onu bugün bitir.",
    "Bugünün önerisi: sevdiğin birine mesaj at, seni düşündüğünü söyle.",
    "Bugünün önerisi: yarım kalan bir işi bugün tamamla.",
    "Bugünün önerisi: biraz yalnız kal, kendinle konuş.",
    "Bugünün önerisi: yeni bir şey dene, alışkanlıklarını kır.",
    "Bugünün önerisi: bir konuda affetmeyi seç, yükün hafiflesin.",
    "Bugünün önerisi: bugünü bir sonraki adımın için planlama fırsatı bil.",
    "Bugünün önerisi: minnettar olduğun üç şeyi aklından geçir.",
  ],
};

// ---- Burç uyumu ----
const ELEMENT_BASE = {
  "ates-ates": 82, "ates-hava": 88, "ates-toprak": 45, "ates-su": 40,
  "hava-hava": 78, "hava-su": 48, "toprak-toprak": 80, "toprak-su": 90,
};

function elementPairScore(e1, e2) {
  const key1 = e1 + "-" + e2;
  const key2 = e2 + "-" + e1;
  return ELEMENT_BASE[key1] ?? ELEMENT_BASE[key2] ?? 55;
}

const COMPAT_TIERS = [
  { min: 85, label: "Kader Ortağı", text: "Aranızda kozmik bir uyum var. Enerjileriniz birbirini öyle güzel tamamlıyor ki, bu bağ tesadüf değil gibi görünüyor." },
  { min: 70, label: "Güçlü Uyum", text: "Aranızdaki bağ oldukça güçlü. Küçük farklılıklar olsa da birbirinizi dengeleme konusunda doğal bir yetenek var." },
  { min: 50, label: "Gelişime Açık", text: "İlk bakışta çok farklı görünseniz de, çaba gösterdiğinizde şaşırtıcı derecede iyi anlaşabilirsiniz." },
  { min: 0, label: "Zorlu Ama İmkansız Değil", text: "Bu eşleşme kolay değil, ama zıtlıklar bazen en öğretici bağları kurar. Sabır ve iletişim burada anahtar." },
];

function compatTier(score) {
  return COMPAT_TIERS.find((t) => score >= t.min);
}

const COMPAT_STRENGTHS = [
  "İkiniz de birbirinizin bağımsızlığına saygı duyuyorsunuz.",
  "Zor zamanlarda birbirinize destek olma konusunda doğal bir uyumunuz var.",
  "Farklı bakış açılarınız birbirinizi tamamlıyor.",
  "İletişim kurmakta zorlanmıyorsunuz, bu nadir bir şey.",
  "Birlikteyken enerjileriniz karşılıklı yükseliyor.",
  "Güven inşa etmekte doğal bir yeteneğiniz var.",
  "Ortak hedefler koymakta zorlanmıyorsunuz.",
  "Mizah anlayışınız benzer, birlikte kolayca gülebiliyorsunuz.",
  "Birbirinizin alanına saygı gösteriyorsunuz.",
  "Değerleriniz büyük ölçüde örtüşüyor.",
];

const COMPAT_CHALLENGES = [
  "Zaman zaman aynı konuda inatlaşabilirsiniz, esneklik önemli.",
  "İletişim tarzınız farklı olabilir, bu bazen yanlış anlaşılmalara yol açabilir.",
  "İkiniz de bağımsız olduğu için ortak karar almak biraz zaman alabilir.",
  "Duygularınızı ifade etme biçiminiz farklı, bu konuda sabırlı olun.",
  "Hız farkınız olabilir; biriniz aceleci, diğeri temkinli olabilir.",
  "Kıskançlık gibi duygulara zemin hazırlayan anlar olabilir, açık iletişim şart.",
  "Öncelikleriniz bazen çakışabilir, uzlaşmayı unutmayın.",
  "Birbirinizin kişisel alanına zaman zaman dikkat etmeniz gerekebilir.",
];

// ---- Kişilik testi ----
const PERSONALITY_QUESTIONS = [
  {
    q: "Yeni bir haftaya başlarken hissettiğin şey genelde nedir?",
    options: [
      { text: "Heyecan, harekete geçmek için sabırsızlanırım.", type: "gunes" },
      { text: "İçimden gelen sessiz bir sezgiyle plan yaparım.", type: "ay" },
      { text: "Merak, keşfedecek yeni bir şey ararım.", type: "yildiz" },
      { text: "Sakinlik, adım adım ilerlemeyi tercih ederim.", type: "toprak" },
    ],
  },
  {
    q: "Bir arkadaş grubunda genelde nasıl bir rolün olur?",
    options: [
      { text: "Enerjiyi yükselten, ortamı canlandıran kişi.", type: "gunes" },
      { text: "Herkesin duygusal durumunu hisseden kişi.", type: "ay" },
      { text: "Yeni fikirler ve planlar öneren kişi.", type: "yildiz" },
      { text: "Herkesin güvendiği, dengeyi sağlayan kişi.", type: "toprak" },
    ],
  },
  {
    q: "Zor bir karar anında ne yaparsın?",
    options: [
      { text: "İçgüdülerimle hızlıca karar veririm.", type: "gunes" },
      { text: "Kalbimin ne dediğini dinlerim.", type: "ay" },
      { text: "Farklı olasılıkları hayal ederim.", type: "yildiz" },
      { text: "Artılarını eksilerini sakince tartarım.", type: "toprak" },
    ],
  },
  {
    q: "Boş bir günün olsa ne yapmak istersin?",
    options: [
      { text: "Dışarı çıkıp insanlarla vakit geçirmek.", type: "gunes" },
      { text: "Yalnız kalıp kendimle baş başa kalmak.", type: "ay" },
      { text: "Hiç gitmediğim bir yeri keşfetmek.", type: "yildiz" },
      { text: "Evimde huzurlu, sakin bir gün geçirmek.", type: "toprak" },
    ],
  },
  {
    q: "Başkaları seni nasıl tanımlar?",
    options: [
      { text: "Karizmatik ve enerjik.", type: "gunes" },
      { text: "Duyarlı ve derin.", type: "ay" },
      { text: "Meraklı ve özgür ruhlu.", type: "yildiz" },
      { text: "Güvenilir ve sakin.", type: "toprak" },
    ],
  },
  {
    q: "Stresli bir anda seni en çok ne rahatlatır?",
    options: [
      { text: "Hareket etmek, bir şeyler yapmak.", type: "gunes" },
      { text: "Duygularımı yazmak ya da müzik dinlemek.", type: "ay" },
      { text: "Ortamı değiştirmek, yeni bir şey denemek.", type: "yildiz" },
      { text: "Rutinime dönmek, düzeni sağlamak.", type: "toprak" },
    ],
  },
  {
    q: "Hayattan en çok neye değer verirsin?",
    options: [
      { text: "Özgürlük ve tutku.", type: "gunes" },
      { text: "Derin bağlar ve anlam.", type: "ay" },
      { text: "Keşif ve merak.", type: "yildiz" },
      { text: "Huzur ve istikrar.", type: "toprak" },
    ],
  },
  {
    q: "Bir hayalin gerçekleşse en çok ne hissedersin?",
    options: [
      { text: "Gurur ve heyecan.", type: "gunes" },
      { text: "Derin bir tatmin ve huzur.", type: "ay" },
      { text: "Yeni hayaller kurma isteği.", type: "yildiz" },
      { text: "Sakin bir minnettarlık.", type: "toprak" },
    ],
  },
  {
    q: "Bir tartışmada genelde nasıl davranırsın?",
    options: [
      { text: "Doğrudan söylerim, geri adım atmam.", type: "gunes" },
      { text: "Karşımdakinin ne hissettiğini anlamaya çalışırım.", type: "ay" },
      { text: "Farklı bir bakış açısı bulup ortamı yumuşatırım.", type: "yildiz" },
      { text: "Sakin kalıp mantıklı bir çözüm ararım.", type: "toprak" },
    ],
  },
  {
    q: "Sana göre mutluluk en çok neyle gelir?",
    options: [
      { text: "Başarmak ve fark edilmek.", type: "gunes" },
      { text: "Sevdiklerimle derin bağ kurmak.", type: "ay" },
      { text: "Yeni bir şey keşfetmek ya da öğrenmek.", type: "yildiz" },
      { text: "Huzurlu ve güvenli bir hayat sürmek.", type: "toprak" },
    ],
  },
];

const PERSONALITY_RESULTS = {
  gunes: {
    title: "Güneş Ruhu",
    tagline: "Doğuştan bir ışık kaynağı",
    text: "Enerjin çevrene ışık saçıyor. Doğuştan bir lidersin, insanları harekete geçirme ve ortama hayat verme konusunda özel bir yeteneğin var. Cesaretin ve tutkun, seni bulunduğun her ortamda fark edilir kılıyor.",
    strengths: ["Karizmatik liderlik", "Yüksek özgüven", "Bulaşıcı enerji"],
    watchFor: "Bazen ışığın çok parlak olduğunda başkalarını gölgede bırakabilirsin — sahneyi paylaşmayı unutma.",
    element: "ates",
  },
  ay: {
    title: "Ay Rüyacısı",
    tagline: "Derin sularda gezinen bir ruh",
    text: "Duyguların derin ve sezgilerin güçlü. Çevrendeki insanların hissettiklerini onlardan önce anlayabiliyorsun. İçe dönük ama son derece anlamlı bir dünyan var; sanat ve derin bağlar seni besliyor.",
    strengths: ["Yüksek empati", "Güçlü sezgi", "Sadakat"],
    watchFor: "Başkalarının duygularını fazla üstlenip kendi ihtiyaçlarını unutabiliyorsun — kendine de zaman ayır.",
    element: "su",
  },
  yildiz: {
    title: "Yıldız Kaşifi",
    tagline: "Sınır tanımayan bir gezgin",
    text: "Merakın seni hiç durmadan yeni ufuklara götürüyor. Rutinden sıkılır, keşfetmeden duramazsın. Özgür ruhun ve yaratıcılığın, çevrendekilere ilham veriyor.",
    strengths: ["Yaratıcılık", "Uyum yeteneği", "Sınırsız merak"],
    watchFor: "Çok fazla yön değiştirmek bazen hiçbir şeyi bitirememene yol açabilir — bir hedefe odaklanmayı dene.",
    element: "hava",
  },
  toprak: {
    title: "Toprak Bilgesi",
    tagline: "Fırtınada bile sağlam duran kaya",
    text: "Sağlam ve güvenilirsin. Çevrendeki insanlar zor zamanlarında sana yönelir, çünkü sen sakinliğin ve dengenin simgesisin. Sabrın ve pratik zekân, en karmaşık durumları bile çözüme kavuşturuyor.",
    strengths: ["Güvenilirlik", "Sabır", "Pratik zeka"],
    watchFor: "Değişime karşı bazen fazla temkinli olabiliyorsun — yeni şeylere biraz daha açık olmayı dene.",
    element: "toprak",
  },
};

// ---- Numeroloji ----
const LIFE_PATH_MEANINGS = {
  1: "Lidersin. Bağımsız, kararlı ve öncü bir ruhun var; kendi yolunu çizmekten korkmuyorsun. Başkalarının onayını beklemeden harekete geçebilme cesaretin, seni doğal bir öncü yapıyor. Zaman zaman yalnız kalmayı göze alsan da bu senin gücünün bir parçası.",
  2: "Denge ve uyum arayan bir ruhsun. Duyarlısın, iş birliğine yatkınsın ve ilişkilerde derinlik ararsın. İnsanlar arasında köprü kurma yeteneğin güçlü; çatışmadan çok uzlaşmayı tercih edersin. Sabrın, en zor durumlarda bile seni ayakta tutan şey.",
  3: "Yaratıcılığın ve ifade gücün öne çıkıyor. Sosyalsin, iletişimin güçlü, hayata renk katıyorsun. Sanatsal bir yönün var, düşüncelerini özgün bir şekilde dile getirebiliyorsun. Enerjini doğru kanalize ettiğinde çevrende gerçek bir ilham kaynağı oluyorsun.",
  4: "Disiplinli ve güvenilirsin. Sağlam temeller kurmayı, planlı ilerlemeyi seversin. Çalışkanlığın ve azmin, uzun vadede büyük başarılar getiriyor. Kestirmelerden çok, sağlam adımlarla ilerlemeyi tercih edersin.",
  5: "Özgürlüğüne düşkünsün. Değişim, macera ve yeni deneyimler seni canlı tutar. Monotonluktan sıkılır, sürekli yeni ufuklar ararsın. Uyum sağlama yeteneğin, seni her ortamda rahat hissettiriyor.",
  6: "Şefkatli ve sorumluluk sahibisin. Ailene ve sevdiklerine karşı derin bir bağlılığın var. Başkalarına bakma, onları koruma içgüdün güçlü. Ev ve ilişkiler senin için hayattaki en büyük önceliklerden biri.",
  7: "İçe dönük ve analitik bir zihnin var. Bilgeliği ve gerçeği araştırmaktan hoşlanırsın. Yüzeysel şeylerle yetinmez, her konunun derinine inmek istersin. Yalnız kalmaktan çekinmez, bu zamanı içsel keşif için kullanırsın.",
  8: "Hırslısın ve maddi/manevi başarı senin için önemli. Güçlü bir irade taşıyorsun. Yönetme ve organize etme konusunda doğal bir yeteneğin var. Zorluklar karşısında geri adım atmak yerine çözüm üretmeyi tercih edersin.",
  9: "İdealistsin. Şefkatin geniş bir çevreye yayılıyor, insanlığa hizmet etme arzusu taşıyorsun. Cömertliğin ve anlayışın, çevrende derin izler bırakıyor. Bazen kendini fazla verip tükenebilirsin, dengeyi unutma.",
  11: "Usta sayı 11: Güçlü bir sezgisel yeteneğin ve ilham verme gücün var. Ruhsal bir öncüsün, çevrene farkında olmadan yön gösteriyorsun. Bu güç seni bazen fazla hassas kılabilir, topraklanmaya özen göster.",
  22: "Usta sayı 22: Büyük hayalleri gerçeğe dönüştürme kapasitesine sahipsin, 'usta inşaatçı' enerjisi taşıyorsun. Vizyonun geniş, ama onu somut adımlara dökme yeteneğin de en az o kadar güçlü.",
  33: "Usta sayı 33: Koşulsuz sevgi ve şefkatle çevrene ilham veren, öğretmen ruhlu bir enerjin var. Başkalarının büyümesine destek olmak senin en doğal yeteneklerinden biri.",
};

const LETTER_VALUES = {
  A: 1, B: 2, C: 3, D: 4, E: 5, F: 6, G: 7, H: 8, I: 9, J: 1, K: 2, L: 3, M: 4,
  N: 5, O: 6, P: 7, Q: 8, R: 9, S: 1, T: 2, U: 3, V: 4, W: 5, X: 6, Y: 7, Z: 8,
  Ç: 3, Ğ: 7, İ: 9, Ö: 6, Ş: 1, Ü: 3,
};

const VOWELS = ["A", "E", "I", "İ", "O", "Ö", "U", "Ü"];

// ---- Aşk uyumu ----
const LOVE_TIERS = [
  { min: 85, label: "Kader Ortağı", text: "Bu isimler arasında kozmik bir uyum seziliyor. Aranızdaki bağ, yıldızların özel bir şekilde hizalandığı anlara işaret ediyor." },
  { min: 65, label: "Güçlü Bağ", text: "Aranızda doğal ve akıcı bir uyum var. Birbirinizi tamamlayan yönleriniz oldukça belirgin." },
  { min: 40, label: "Gelişebilir", text: "Şu an tam bir uyum olmasa da, zaman ve iletişimle bu bağ güçlenmeye çok açık." },
  { min: 0, label: "Zıt Kutuplar", text: "Çok farklı enerjiler taşıyorsunuz, ama bazen en ilginç hikayeler böyle başlar." },
];

function loveTier(score) {
  return LOVE_TIERS.find((t) => score >= t.min);
}

function subscoreLabel(score) {
  if (score >= 80) return "Çok Güçlü";
  if (score >= 60) return "Güçlü";
  if (score >= 40) return "Orta";
  return "Gelişmeye Açık";
}

// ---- Rüya tabiri ----
const DREAM_DICTIONARY = {
  "su": "Berrak su görmek huzuru, bulanık su ise içinde bulunduğun karışıklığı simgeler. Duygusal durumunun bir yansıması olabilir. Akan su genelde hayatındaki değişimin doğal seyrinde ilerlediğine işaret eder.",
  "yılan": "Gizli bir tehdide ya da fark etmediğin bir düşmana işaret edebilir. Aynı zamanda dönüşüm ve yenilenmenin de simgesidir. Deri değiştiren bir yılan görmek, hayatındaki bir dönemi geride bıraktığını gösterebilir.",
  "uçmak": "Özgürlük arayışını ve hayatındaki kontrolü ele alma isteğini temsil eder. Genelde olumlu bir işarettir. Kolayca uçmak özgüvenini, zorlanarak uçmak ise önündeki engelleri simgeler.",
  "düşmek": "Hayatında kontrolü kaybettiğin hissine ya da güvensizliğe işaret edebilir. Sık tekrarlanıyorsa, uyanık hayatında ele almadığın bir kaygı olabilir.",
  "diş dökülmesi": "Kaygı, kayıp korkusu ya da özgüven meseleleriyle ilişkilendirilir. Bazı yorumlara göre önemli bir kararın eşiğinde olduğunun işaretidir.",
  "ölüm": "Genelde gerçek bir kaybı değil, hayatındaki bir dönemin sona erip yenisinin başladığını simgeler. Dönüşüm ve yeniden doğuşla ilişkilendirilir.",
  "deniz": "Bilinçaltının derinliklerini temsil eder. Sakin deniz huzuru, dalgalı deniz iç çalkantıyı gösterir. Denizin derinliklerine dalmak, kendini keşfetme isteğine işaret edebilir.",
  "ev": "Kendi benliğini ve iç dünyanı simgeler. Evin durumu, o an ki ruh halinle bağlantılı olabilir. Yeni bir ev görmek, kimliğinde bir değişimin habercisi olabilir.",
  "araba": "Hayatındaki yönünü ve kontrolünü temsil eder. Kontrolsüz bir araba, hayatta kontrolü kaybetme korkusuna işaret edebilir. Sürücü koltuğunda olmak, hayatının dizginlerini elinde tuttuğunu gösterir.",
  "bebek": "Yeni bir başlangıcı, henüz olgunlaşmamış bir fikri ya da projeyi simgeler. Bazen de içindeki masumiyete duyduğun özlemi yansıtır.",
  "düğün": "Hayatındaki iki farklı yönün birleşmesini ya da önemli bir taahhüdü temsil eder. Gerçek bir evlilik isteğinden çok, bir bütünleşme arzusunu gösterebilir.",
  "sınav": "Kendini kanıtlama baskısı ya da bir konuda yetersizlik hissi ile ilişkilendirilir. Hazırlıksız olduğun bir sınav, hayatta hazır hissetmediğin bir durumu simgeler.",
  "kaybolmak": "Hayatında bir yön kaybı ya da karar verme güçlüğü yaşadığının işareti olabilir. Yolunu bulmak için içsel rehberliğe ihtiyacın olduğunu gösterebilir.",
  "takip edilmek": "Kaçındığın bir sorun ya da kendi duygularınla yüzleşmekten kaçtığını gösterebilir. Seni takip eden şeyin ne olduğu, kaçtığın konu hakkında ipucu verebilir.",
  "ateş": "Tutku, öfke ya da dönüşümü simgeler. Bağlama göre yıkıcı ya da arındırıcı olabilir. Kontrollü bir ateş, içindeki tutkuyu doğru yönettiğini gösterir.",
  "para": "Öz değer duygunla ya da güvenlik ihtiyacınla ilgilidir, her zaman gerçek parayla ilgili değildir. Para bulmak, kendine olan güveninin arttığına işaret edebilir.",
  "altın": "Değerli bulduğun bir şeyi ya da içsel zenginliğini temsil eder. Bazen fark etmediğin bir yeteneğine işaret eder.",
  "örümcek": "Karmaşık bir durumun içinde sıkışmış hissetmenle ya da yaratıcı enerjinle ilişkilendirilir. Örümcek ağı, seni bağlayan bir durumu simgeler.",
  "köpek": "Sadakat, dostluk ve güven duygularını simgeler. Saldırgan bir köpek, güvendiğin birinden gelen bir ihanet korkusuna işaret edebilir.",
  "kedi": "Bağımsızlık, gizem ve sezgilerinle bağlantılıdır. Dişil enerjiyi ve içsel bilgeliği de temsil edebilir.",
  "kan": "Yaşam enerjisi ya da güçlü duygusal bir olayla ilişkilendirilir. Aile bağlarına da işaret edebilir.",
  "yangın": "Kontrolden çıkan bir durum ya da bastırılmış öfkeyi simgeler. Aynı zamanda köklü bir değişimin habercisi olabilir.",
  "deprem": "Hayatındaki temellerin sarsıldığı, büyük bir değişim döneminde olduğun anlamına gelebilir. Güvende hissettiğin alanların sorgulandığını gösterebilir.",
  "uçak": "Büyük hedeflere hızla ilerleme isteğini ya da hayatındaki büyük bir sıçramayı temsil eder. Uçağı kaçırmak, bir fırsatı kaçırma korkusunu simgeler.",
  "yol": "Hayat yolculuğunu ve şu anki yönünü simgeler. Dolambaçlı bir yol, kararsızlığa işaret edebilir. Düz ve açık bir yol, netliğe kavuştuğunu gösterir.",
  "merdiven": "Kişisel gelişim ya da hedeflerine doğru ilerleyişini temsil eder. Yukarı çıkmak ilerlemeyi, aşağı inmek içe dönüşü simgeler.",
  "anahtar": "Bir çözüme, fırsata ya da yeni bir kapıya açılan imkana işaret eder. Kaybolan bir anahtar, kaçırdığın bir fırsatı simgeleyebilir.",
  "ayna": "Kendini nasıl gördüğünle, öz farkındalığınla ilgilidir. Kırık bir ayna, kendine bakışında bir kırılmayı gösterebilir.",
  "saç kesimi": "Kimliğinde ya da imajında bir değişim isteğini simgeler. Saç kaybetmek, kontrol kaybı korkusuyla ilişkilendirilir.",
  "balık": "Bilinçaltı, bereket ve duygusal derinlikle ilişkilendirilir. Çok sayıda balık görmek, bolluk ve fırsat işareti olabilir.",
  "hamile kalmak": "Yeni bir fikrin ya da projenin hayatında filizlenmeye başladığını gösterebilir. Yaratıcı bir sürecin başlangıcına işaret eder.",
  "eski sevgili": "Genelde o kişiyle değil, o dönemde hissettiğin duygularla ilgilidir. Geçmişte kalan bir özelliği şu an aradığını gösterebilir.",
  "kavga": "İçsel bir çatışmayı ya da bastırdığın bir gerilimi yansıtabilir. Kiminle kavga ettiğin, o kişinin temsil ettiği özelliklerle ilgilidir.",
  "ağlamak": "Bastırılmış duyguların yüzeye çıkma ihtiyacını gösterir, genelde rahatlatıcıdır. Rüyada ağlamak, uyanınca hafiflemeyle sonuçlanabilir.",
  "gülmek": "İç huzurunu ve hayata karşı olumlu bakış açını yansıtır. Kontrolsüz bir kahkaha, bastırdığın neşenin dışa vurumu olabilir.",
  "uçurum": "Bilinmeyen bir riske karşı duyduğun korkuyu simgeler. Uçurumun kenarında durmak, önemli bir karar anında olduğunu gösterebilir.",
  "karanlık": "Bilinmeyenden duyulan korkuyu ya da henüz keşfedilmemiş bir yönünü temsil eder. Bazen bilinçaltının henüz aydınlatılmamış bir parçasına işaret eder.",
  "ışık": "Umut, netlik ve rehberliği simgeler. Uzaktaki bir ışık, zorlu bir dönemin sonunun yaklaştığına işaret edebilir.",
  "yolculuk": "Kişisel dönüşüm sürecinde olduğunu ve yeni bir aşamaya geçtiğini gösterir. Ulaşım aracının türü, yolculuğun hızını/tarzını simgeler.",
  "okul": "Hayatta öğrenmeye devam ettiğin bir alanı ya da geçmişten kalan bir kaygıyı temsil eder. Eski okuluna dönmek, geçmişle yüzleşme ihtiyacına işaret edebilir.",
  "hırsız": "Bir şeyini kaybetme korkusu ya da güven meselesiyle ilişkilendirilir. Neyin çalındığı, neyi kaybetmekten korktuğunla ilgili ipucu verir.",
  "kapı": "Yeni bir fırsatı ya da hayatındaki bir geçiş dönemini simgeler. Kilitli bir kapı, önündeki bir engele işaret edebilir.",
  "pencere": "Dışarıya, yeni olasılıklara açılan bakış açını temsil eder. Kırık bir pencere, güvenlik kaygısını gösterebilir.",
  "gökyüzü": "Sınırsız potansiyeli ve özgürlük arayışını simgeler. Açık ve berrak gökyüzü, zihinsel netliğe işaret eder.",
  "yıldız": "Umut, hedefler ve rehberlik arayışını temsil eder. Parlayan bir yıldız, yakın zamanda gerçekleşecek bir dileği simgeleyebilir.",
  "ay": "Duygusal döngülerini ve bilinçaltı dünyanı simgeler. Dolunay, duygusal yoğunluğun zirvede olduğuna işaret edebilir.",
  "güneş": "Yaşam enerjisi, netlik ve öz güveni temsil eder. Doğan güneş, yeni bir başlangıcı müjdeler.",
  "uçurtma": "Hayallerinin peşinden gitme isteğini ve özgürlük arayışını simgeler.",
  "orman": "Bilinmeyeni ve keşfedilmemiş potansiyelini temsil eder. Kaybolduğun bir orman, kararsızlık dönemine işaret edebilir.",
  "dağ": "Önündeki büyük bir hedefi ya da aşman gereken bir zorluğu simgeler. Zirveye ulaşmak, başarıya yaklaştığını gösterir.",
  "köprü": "Bir geçiş dönemini, iki durum arasında bağ kurma ihtiyacını temsil eder.",
  "kuş": "Özgürlüğü ve ruhsal yükselişi simgeler. Kafeste bir kuş, kısıtlanmışlık hissine işaret edebilir.",
  "kelebek": "Dönüşümü ve kişisel gelişimi temsil eder, genelde olumlu bir değişimin habercisidir.",
  "yumurta": "Yeni bir fikrin ya da potansiyelin henüz açığa çıkmamış halini simgeler.",
  "hastalık": "Hayatının bir alanında dengesizlik hissettiğine işaret edebilir, genelde gerçek bir sağlık sorunuyla ilgili değildir.",
  "silah": "Kendini savunma ihtiyacını ya da bastırılmış öfkeyi simgeler.",
  "hapis": "Hayatında kendini kısıtlanmış hissettiğin bir durumu temsil eder.",
  "uçak düşmesi": "Kontrol kaybı korkusunu ve büyük bir hedefin başarısız olma endişesini simgeler.",
  "telefon": "İletişim ihtiyacını ya da söylenmemiş bir sözü temsil eder. Çalmayan bir telefon, göz ardı edilme korkusuna işaret edebilir.",
  "yemek yemek": "Hayattaki doyum ve tatmin arayışını simgeler. Paylaşılan bir yemek, sosyal bağların önemine işaret eder.",
  "dişler": "Özgüven, imaj ve iletişim biçiminle ilgilidir.",
  "yüzmek": "Duygularınla baş etme biçimini simgeler. Rahat yüzmek duygusal dengeyi, boğulmak ise bunalmışlığı gösterir.",
  "kayıp eşya": "Hayatında ihmal ettiğin bir şeye, ya da güvensizlik hissine işaret edebilir.",
  "yabancı biri": "Kendi kişiliğinin henüz tanımadığın bir yönünü simgeler.",
  "çıplak olmak": "Savunmasız hissetme, başkalarının seni gerçek haliyle görmesinden duyduğun kaygıyı simgeler. Bazen de saklamayı bıraktığın bir şeyin işareti olabilir.",
  "at": "Güç, özgürlük ve ilerleme arzusunu temsil eder. Dizginlenmiş bir at, bastırdığın bir enerjiye işaret edebilir.",
  "aslan": "Güç, cesaret ve liderlik arzusunu simgeler. Aynı zamanda hayatındaki otorite figürleriyle ilişkilendirilir.",
  "kurt": "Hem tehdit hem de bağımsızlık simgesidir. Sürü halinde kurtlar, toplumsal baskı hissini gösterebilir.",
  "inek": "Bereket, bolluk ve şefkati simgeler. Huzurlu bir inek görmek, maddi güvenlik arayışına işaret edebilir.",
  "fare": "Küçük ama sürekli seni rahatsız eden bir endişeyi ya da göz ardı ettiğin bir sorunu temsil eder.",
  "tavuk": "Günlük hayattaki küçük kaygıları ve ev/aile ile ilgili konuları simgeler.",
  "cin": "Kontrol edemediğin, bilinmeyen güçlere duyulan korkuyu simgeler; genelde bastırılmış kaygılarla ilişkilendirilir.",
  "nazar": "Başkalarının seni kıskandığına ya da olumsuz enerjiden korunma ihtiyacına işaret eder.",
  "hayalet": "Geçmişten kalan çözülmemiş bir mesele ya da unutamadığın bir anıyı simgeler.",
  "melek": "Korunma, rehberlik ve iç huzur arayışını temsil eder.",
  "şeytan": "İçindeki bastırılmış dürtüleri ya da bir konuda kendine karşı savaştığın ayartmayı simgeler.",
  "cenaze": "Ölümle değil, hayatındaki bir dönemin ya da alışkanlığın sona erdiğiyle ilişkilendirilir.",
  "mezarlık": "Geçmişle yüzleşme ve geride bıraktığın şeyleri kabullenme sürecini simgeler.",
  "doğum": "Yeni bir başlangıcı, hayatına giren taze bir fikri ya da fırsatı temsil eder.",
  "boşanma": "Hayatındaki bir bağın ya da alışkanlığın sona erme ihtiyacını simgeler, gerçek bir evlilikle ilgili olmak zorunda değildir.",
  "aldatılmak": "Güven meselelerini ve içindeki güvensizlik hissini yansıtır, gerçek bir ihanetin habercisi değildir.",
  "kaza": "Kontrolü kaybetme korkusunu ya da hayatında ani bir değişim beklentisini simgeler.",
  "ameliyat": "İyileşme ihtiyacı duyduğun bir konuyu ya da köklü bir değişim isteğini temsil eder.",
  "hastane": "İyileşme, bakım ihtiyacı ya da hayatındaki bir konunun 'tedavi' gerektirdiğini simgeler.",
  "doktor": "Rehberlik arayışını ve bir konuda uzman desteğine ihtiyaç duyduğunu gösterir.",
  "asker": "Disiplin, görev bilinci ya da hayatındaki bir mücadeleyi simgeler.",
  "savaş": "İçsel bir çatışmayı ya da hayatında sürmekte olan bir mücadeleyi temsil eder.",
  "sel": "Bastırılmış duyguların aniden yüzeye çıkmasını simgeler, genelde yoğun bir duygusal dönemle ilişkilendirilir.",
  "yağmur": "Arınma ve yenilenmeyi simgeler. Hafif yağmur huzuru, sağanak ise yoğun duyguları temsil eder.",
  "kar": "Saflık, durgunluk ya da duygusal bir donukluğu simgeler.",
  "gökkuşağı": "Umut, zorlu bir dönemin ardından gelen iyileşmeyi temsil eder.",
  "fırtına": "Hayatındaki kontrolsüz bir durumu ya da bastırılmış duygusal yoğunluğu simgeler.",
  "yüzük": "Bağlılık, taahhüt ya da bir döngünün tamamlanmasını temsil eder.",
  "gelinlik": "Yeni bir başlangıca hazır olma isteğini ya da beklentilerini simgeler.",
  "elbise": "Başkalarına nasıl göründüğünle, imajınla ilgilidir. Eski ya da yıpranmış bir elbise, özgüven meselesine işaret edebilir.",
  "ayakkabı": "Hayat yolunda attığın adımları ve yönünü simgeler. Dar bir ayakkabı, kısıtlanmışlık hissine işaret edebilir.",
  "asansör": "Hayatındaki iniş çıkışları ve statü ya da duygu değişimlerini simgeler.",
  "tren": "Hayatının önceden belirlenmiş bir yönde ilerlediği hissini simgeler, kaçırılan bir tren fırsat kaygısına işaret eder.",
  "gemi": "Duygusal yolculuğunu ve bilinmeyene doğru ilerleyişini simgeler.",
  "bisiklet": "Kendi çabanla ilerleme ve denge kurma yeteneğini simgeler.",
  "kuyu": "Bilinçaltının derinliklerini ve henüz keşfetmediğin iç kaynaklarını simgeler.",
  "mağara": "İçe dönüklüğü, saklanma ihtiyacını ya da henüz keşfedilmemiş potansiyelini temsil eder.",
  "ada": "Yalnızlık ihtiyacını ya da başkalarından izole hissetmeni simgeler.",
  "gölge": "Kendinin bastırdığın, kabul etmediğin bir yönünü temsil eder.",
  "ikiz": "İçindeki zıt yönleri ya da bir karardaki ikilemi simgeler.",
  "balon": "Hafiflik arzusunu ya da gerçekçi olmayan bir beklentiyi simgeler; patlayan balon hayal kırıklığına işaret edebilir.",
  "çiçek": "Büyüme, güzellik ve yeni bir duygunun filizlenmesini simgeler.",
  "ağaç": "Kişisel gelişimini ve köklerinle olan bağını temsil eder. Güçlü bir ağaç istikrarı simgeler.",
  "bal": "Ödül, tatlı bir haber ya da emeğinin karşılığını almayı simgeler.",
  "ekmek": "Temel ihtiyaçlarını ve günlük hayattaki güvenliğini simgeler.",
  "süt": "Bakım, beslenme ve şefkat ihtiyacını simgeler.",
  "elma": "Ayartı, merak ya da yeni bir bilgiyle tanışmayı simgeler.",
  "armut": "Olgunlaşma sürecini ve emeğinin karşılığını almaya yaklaştığını simgeler.",
  "üzüm": "Bereket ve bolluğu, salkım halinde olması ise çevrendeki topluluğu simgeler.",
  "karpuz": "Yaz bereketini ve rahatlama ihtiyacını simgeler.",
  "muz": "Enerji ve pratik bir çözüm ihtiyacını simgeler.",
  "çilek": "Küçük ama tatlı bir mutluluğu, hayattaki basit zevkleri simgeler.",
  "nar": "Bereket, bolluk ve içindeki çok yönlülüğü simgeler.",
  "portakal": "Canlılık, sağlık ve neşeyi simgeler.",
  "limon": "Ferahlama ihtiyacını ya da hayatındaki ekşi/zor bir durumu simgeler.",
  "patates": "Temel ihtiyaçlarını ve sadeleşme arayışını simgeler.",
  "soğan": "Bir konunun katman katman açığa çıkması gerektiğine işaret eder.",
  "sarımsak": "Kendini koruma içgüdünü ve olumsuz enerjiden uzaklaşma isteğini simgeler.",
  "biber": "Hayatına heyecan ya da gerginlik katan bir durumu simgeler.",
  "domates": "Günlük hayattaki küçük bereket ve emeğin meyvesini simgeler.",
  "çay": "Sohbet, samimiyet ve yavaşlama ihtiyacını simgeler.",
  "kahve": "Uyanıklık, netlik arayışı ya da önemli bir sohbeti simgeler.",
  "şarap": "Kutlama isteğini ya da bastırılmış duyguların gevşemesini simgeler.",
  "tuz": "Hayata kattığın değeri ve dengeyi simgeler.",
  "şeker": "Küçük bir mutluluk anını ya da tatlı bir haberi simgeler.",
  "çikolata": "Kendine bir ödül verme ihtiyacını simgeler.",
  "pasta": "Kutlama, paylaşım ve özel bir anı simgeler.",
  "peynir": "Sabır isteyen, olgunlaşmakta olan bir sürece işaret eder.",
  "et": "Yaşam gücünü ve temel ihtiyaçlarını simgeler.",
  "pilav": "Bereket, aile sofrası ve doyum hissini simgeler.",
  "çorba": "İyileşme, huzur ve şefkat ihtiyacını simgeler.",
  "göz": "Farkındalığını ve bir konuyu net görme ihtiyacını simgeler.",
  "el": "Eylemlerini ve bir şeyi kontrol etme gücünü simgeler.",
  "ayak": "Hayattaki yönünü ve ilerleme biçimini simgeler.",
  "saç": "Kimliğini ve kendine bakışını simgeler; kesilen saç bir değişim isteğine işaret eder.",
  "kalp": "Duygusal dünyanı ve sevme kapasiteni simgeler.",
  "kafa": "Düşüncelerini ve zihinsel netliğini simgeler.",
  "burun": "Sezgilerini ve bir durumu 'koklama' yeteneğini simgeler.",
  "kulak": "Dinleme ihtiyacını ya da duymak istemediğin bir şeyi simgeler.",
  "dil": "İfade biçimini ve söylemekten çekindiğin bir sözü simgeler.",
  "sakal": "Olgunluk, bilgelik ya da erkeksi güç arayışını simgeler.",
  "öğretmen": "Rehberlik ihtiyacını ya da öğrenmen gereken bir dersi simgeler.",
  "avukat": "Kendini savunma ihtiyacını ya da adalet arayışını simgeler.",
  "mühendis": "Hayatını yeniden inşa etme, sistemli çözüm bulma isteğini simgeler.",
  "aşçı": "Yaratıcılığını ve hayatına yeni bir tat katma isteğini simgeler.",
  "berber": "Kendini yenileme ve imaj değişikliği isteğini simgeler.",
  "çiftçi": "Emek verdiğin bir şeyin meyvesini toplama zamanının yaklaştığını simgeler.",
  "ressam": "Kendini özgürce ifade etme ihtiyacını simgeler.",
  "müzisyen": "Duygularını dışa vurma ve uyum arayışını simgeler.",
  "yazar": "İçindeki sesi duyurma ve anlatma ihtiyacını simgeler.",
  "masa": "Toplumsal bağlarını ve paylaşımı simgeler.",
  "sandalye": "Hayattaki konumunu ve statünü simgeler.",
  "yatak": "Dinlenme, mahremiyet ve iç dünyanı simgeler.",
  "halı": "Ait olma hissini ve güvenli bir zemin arayışını simgeler.",
  "lamba": "Netlik, rehberlik ve umut arayışını simgeler.",
  "saat": "Zaman baskısını ya da bir konuda geç kaldığın hissini simgeler.",
  "dolap": "Saklı tuttuğun duygularını ya da geçmişini simgeler.",
  "mutfak": "Dönüşüm ve besleyici enerjini simgeler.",
  "banyo": "Arınma, temizlenme ve yenilenme ihtiyacını simgeler.",
  "şapka": "Üstlendiğin bir rolü ya da kimliği simgeler.",
  "çanta": "Taşıdığın sorumlulukları ve yükleri simgeler.",
  "gözlük": "Bir konuyu daha net görme ihtiyacını simgeler.",
  "kemer": "Kendini disipline etme ya da kontrol ihtiyacını simgeler.",
  "eldiven": "Bir konuya mesafeli yaklaşma isteğini simgeler.",
  "atkı": "Korunma ihtiyacını ve sıcaklık arayışını simgeler.",
  "küpe": "Kendini süsleme ve fark edilme isteğini simgeler.",
  "kolye": "Değer verdiğin bir bağı ya da anıyı simgeler.",
  "bilezik": "Bir taahhüdü ya da sürekliliği simgeler.",
  "kırmızı": "Tutku, enerji ve güçlü duyguları simgeler.",
  "siyah": "Bilinmeyeni, gizemi ya da yası simgeler.",
  "beyaz": "Saflığı, yeni bir başlangıcı simgeler.",
  "mavi": "Huzuru, sakinliği ve güveni simgeler.",
  "yeşil": "Büyümeyi, umudu ve yenilenmeyi simgeler.",
  "sarı": "Neşeyi, zekayı ve enerjiyi simgeler.",
  "mor": "Maneviyatı, gizemi ve yaratıcılığı simgeler.",
  "pembe": "Şefkati, sevgiyi ve masumiyeti simgeler.",
  "anne": "Koruma, şefkat ve köklerinle olan bağını simgeler.",
  "baba": "Otorite, güven ve rehberlik ihtiyacını simgeler.",
  "kardeş": "Rekabet ya da dayanışma temalı bir ilişkiyi simgeler.",
  "çocuk": "İçindeki masumiyeti ve yeni bir başlangıcı simgeler.",
  "arkadaş": "Destek ihtiyacını ve sosyal bağlarını simgeler.",
  "komşu": "Sınırların ve günlük hayattaki küçük gerginliklerin simgesidir.",
  "patron": "Otoriteyle ilişkini ve kontrol meselelerini simgeler.",
  "korku": "Yüzleşmen gereken bir konuyu simgeler.",
  "mutluluk": "İçsel dengeni ve tatmin düzeyini simgeler.",
  "öfke": "Bastırılmış bir duyguyu ya da haksızlık hissini simgeler.",
  "utanç": "Kendine karşı eleştirel yaklaşımını simgeler.",
  "pişmanlık": "Geçmişle barışma ihtiyacını simgeler.",
  "özlem": "Kaybettiğin ya da uzak kaldığın bir şeye duyduğun bağlılığı simgeler.",
  "koşmak": "Bir şeyden kaçma ya da bir hedefe ulaşma çabanı simgeler.",
  "futbol": "Rekabet, ekip ruhu ve hedefe odaklanmayı simgeler.",
  "yarış": "Rekabet duygunu ve kendini kanıtlama isteğini simgeler.",
  "dövüş": "İçsel bir çatışmayı ya da kendini savunma ihtiyacını simgeler.",
  "bilgisayar": "Bilgiye erişim ve zihinsel yoğunluğu simgeler.",
  "internet": "Bağlantı kurma ihtiyacını ve bilgi akışını simgeler.",
  "sosyal medya": "Nasıl görüldüğün ve onay arayışınla ilgilidir.",
  "mesaj": "Söylenmemiş bir sözü ya da beklenen bir haberi simgeler.",
  "fotoğraf": "Anıları ve geçmişe duyduğun bağlılığı simgeler.",
  "video": "Hayatını dışarıdan izliyormuş gibi hissettiğin bir dönemi simgeler.",
  "market": "Günlük ihtiyaçlarını ve seçim yapma sürecini simgeler.",
  "alışveriş merkezi": "Seçenek bolluğunu ve karar verme güçlüğünü simgeler.",
  "plaj": "Rahatlama, sınır ve bilinçaltıyla buluşma noktasını simgeler.",
  "park": "Dinlenme ve doğayla bağlantı ihtiyacını simgeler.",
  "otel": "Geçici bir dönemde olduğunu ya da köklerinden uzak hissettiğini simgeler.",
  "restoran": "Sosyal ihtiyaçlarını ve doyum arayışını simgeler.",
  "ofis": "Sorumluluklarını ve kariyer kaygılarını simgeler.",
  "fabrika": "Verimlilik baskısını ve rutin hissini simgeler.",
  "çiftlik": "Emek, sabır ve doğayla olan bağını simgeler.",
  "böcek": "Küçük ama seni rahatsız eden bir detayı simgeler.",
  "arı": "Çalışkanlığı ve topluluk içindeki rolünü simgeler.",
  "karınca": "Sabır, disiplin ve küçük adımlarla ilerlemeyi simgeler.",
  "kurbağa": "Dönüşüm sürecini ve uyum yeteneğini simgeler.",
  "timsah": "Gizli bir tehlikeyi ya da gösterişin altındaki riski simgeler.",
  "ejderha": "Büyük bir güç ya da aşman gereken bir korkuyu simgeler.",
  "ayı": "Korunma içgüdünü ve bastırılmış öfkeyi simgeler.",
  "tavşan": "Bereketi, hız ve çekingenliği simgeler.",
  "geyik": "Zarafeti ve dikkatli ilerleme ihtiyacını simgeler.",
  "fil": "Güç, hafıza ve sabrı simgeler.",
  "maymun": "Oyunbazlığı ya da taklit etme eğilimini simgeler.",
  "papağan": "Başkalarının sözlerini tekrar etme ya da özgün olamama kaygısını simgeler.",
  "baykuş": "Bilgeliği ve gizli bilgilere duyulan merakı simgeler.",
  "deve": "Sabrı ve zorluklara dayanıklılığı simgeler.",
  "motosiklet": "Bağımsızlık ve hız arzusunu simgeler.",
  "kamyon": "Taşıdığın büyük bir sorumluluğu simgeler.",
  "helikopter": "Durumlara yukarıdan, geniş bir bakış açısıyla bakma ihtiyacını simgeler.",
  "roket": "Hızlı bir yükselişi ya da büyük bir hedefi simgeler.",
  "tekne": "Duygusal dalgalanmalarla baş etme biçimini simgeler.",
  "kasırga": "Kontrolünü kaybettiğin, yoğun bir değişim dönemini simgeler.",
  "çığ": "Küçük bir sorunun büyümeden önce fark edilmesi gerektiğine işaret eder.",
  "patlama": "Bastırılmış duyguların aniden açığa çıkmasını simgeler.",
  "dua etmek": "İçsel huzur arayışını ve bir konuda rehberlik ihtiyacını simgeler.",
  "kumar": "Hayatında aldığın bir riski ve belirsizlikle ilişkini simgeler.",
  "piyango": "Beklenmedik bir şansı ya da kolay çözüm arayışını simgeler.",
  "nişan": "Bir taahhüde hazırlanma sürecini simgeler.",
  "oyun oynamak": "Hayata karşı hafif ve keyifli bir yaklaşım ihtiyacını simgeler.",
  "dans etmek": "Özgür ifade ve içsel uyumu simgeler.",
  "şarkı söylemek": "İçindeki duyguları dışa vurma ihtiyacını simgeler.",
  "konser": "Toplu coşku ve paylaşım ihtiyacını simgeler.",
  "sinema": "Hayatını dışarıdan izleme, gözlemleme ihtiyacını simgeler.",
  "tiyatro": "Hayatında oynadığın bir rolü ya da takındığın maskeyi simgeler.",
  "ceket": "Kendini koruma ve dış dünyaya karşı zırhlanma ihtiyacını simgeler.",
  "pantolon": "Güven ve kontrol duygunu simgeler.",
  "gömlek": "Dışarıya sunduğun imajı simgeler.",
  "çorap": "Küçük ama gözden kaçan bir detayı simgeler.",
  "yorgan": "Güvenlik, sıcaklık ve korunma ihtiyacını simgeler.",
  "yastık": "Dinlenme ve rahatlama ihtiyacını simgeler.",
  "bahçe": "Kişisel gelişimini ve emek verdiğin alanları simgeler.",
  "çim": "Tazelik, büyüme ve doğal döngüyü simgeler.",
  "taş": "Sağlamlığı ya da önündeki bir engeli simgeler.",
  "kum": "Geçici olanı ve zamanın akışını simgeler.",
  "çöl": "Yalnızlık hissini ya da duygusal bir kuraklığı simgeler.",
  "volkan": "Bastırılmış öfkenin patlamaya hazır olduğunu simgeler.",
  "gökdelen": "Büyük hedeflerini ve yükselme arzunu simgeler.",
  "köy": "Sadeliğe ve köklerine duyduğun özlemi simgeler.",
  "şehir": "Sosyal hayatını ve hareketli bir dönemi simgeler.",
  "harita": "Yön arayışını ve hayatındaki büyük resmi görme ihtiyacını simgeler.",
  "öldüğünü görmek": "Genelde gerçek bir ölüm kehaneti değildir — çoğu yorumda tam tersine, o kişinin uzun ve sağlıklı bir hayat süreceğine işaret eder. Aynı zamanda o kişiyle ilişkinde bir dönemin kapandığını da simgeleyebilir.",
  "boğulmak": "Hayatında nefes alamadığın, bunaldığın bir durumla ilişkilendirilir — iş yükü, ilişki ya da duygusal bir baskı olabilir. Bazı yorumlara göre ise kapalı bir kapının açılacağına, rahatlamanın yakın olduğuna işaret eder.",
  "ısırılmak": "Bir konuda kendini savunmasız hissettiğini ya da çevrende güvenmediğin birinin varlığını gösterebilir. Seni ısıran şeyin ne olduğu, kimden/neyden tedirgin olduğun konusunda ipucu verir.",
  "vurulmak": "Beklenmedik bir haber, kayıp ya da hayal kırıklığına işaret edebilir. Aynı zamanda içindeki bir kırılganlığın veya savunmasızlık hissinin yansıması olabilir.",
  "evlenmek": "Hayatındaki iki farklı yönün birleşmesini, önemli bir taahhüdü ya da yeni bir sorumluluğa hazır olma hissini temsil eder. Gerçek bir evlilik isteğinden çok, bütünleşme ve kararlılık arzusunu yansıtabilir.",
  "sevgili": "Duygusal ihtiyaçlarını, yakınlık arayışını ya da mevcut ilişkindeki bir dinamiği simgeler. Rüyadaki sevgili gerçek biri değilse bile, o kişinin temsil ettiği özellikler önemlidir.",
  "yılan sokması": "Fark etmediğin bir tehdidin ya da ihanetin seni yakaladığı hissine işaret edebilir. Aynı zamanda zorlu ama dönüştürücü bir deneyimin habercisi olarak da yorumlanır.",
  "düşman": "Aslında dışarıdaki biriyle değil, kendi iç çatışmanla ilgili olabilir — bastırdığın bir korkunun ya da kendine karşı eleştirel sesin simgesi olabilir.",
  "tokat": "Ani bir uyanışı, gerçekle yüzleşme anını ya da bastırdığın bir öfkeyi simgeler. Kimin tokat attığı/yediği, çatışmanın kaynağına dair ipucu verebilir.",
  "cinayet": "Genellikle gerçek bir şiddetle değil, hayatındaki bir şeyin (bir alışkanlık, bir ilişki, eski bir kimlik) kesin olarak sona erdirilmesiyle ilişkilendirilir.",
  "aşk": "Kendine ya da hayata karşı duyduğun bağlılığı, özlemi ya da yeni bir bağ kurma isteğini simgeler. Bazen de içindeki şefkat ihtiyacının bir yansımasıdır.",
  "işten kovulmak": "Doğrudan iş kaybı kehaneti değildir — daha çok yetersizlik korkusunu, değersiz hissetme endişesini ya da mevcut işinden memnuniyetsizliğini yansıtır.",
  "terfi": "Kendi potansiyeline duyduğun güveni ya da başarı konusundaki beklentilerini simgeler. Hak ettiğin bir takdiri bekleme hissiyle de ilişkilendirilebilir.",
  "burun kanaması": "Enerjinin veya duygularının kontrolsüzce dışa vurduğu bir dönemi simgeler. Bastırdığın bir gerginliğin fiziksel bir çıkış yolu araması olarak da yorumlanır.",
};
